name: Copy Files Workflow

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source Repository (format: owner/repo)'
        required: true
      source_path:
        description: 'File/Directory Path to Copy from Source Repo'
        required: true
      source_pat:
        description: 'PAT for Source Repo (if private, leave blank if public)'
        required: false
      pat:
        description: 'PAT for operations, defaults to using GITHUB_TOKEN'
        required: false

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files/Folders within Current Repository
        uses: neerajadobe93/actions@v0.0.3
        with:
          source_repo: ${{ inputs.source_repo }}
          source_path: ${{ inputs.source_path }}
          source_pat: ${{ inputs.source_pat }}
          pat: ${{ inputs.pat }}
